spring:
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
  devtools:
    add-properties: false
