spring:
  application:
    name: notification-service
  profiles:
    active: default,dev
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${GOOGLE_SMTP_USERNAME}
    password: ${GOOGLE_SMTP_PASSWORD}
    ssl:
      enabled: true
mq:
  listen:
    code-generated-queue: code.generated.queue
mail:
  login-code:
    theme: "Parking Routing App | Code for log in"
    text: "Hello there.\nHere is your code for log in:\n\n[%s]\n\nDo not send this code to anyone!"
sms-sender:
  api-id: ${SMS_SERVICE_API_ID}
  endpoint: "https://sms.ru/sms/send?api_id=%s&to=7%s&msg=%s&json=1"
  code-text: "%s - code for your login in Parking Routing App."

server:
  port: 0