#file: noinspection undefined
spring:
  application:
    name: identity-service
  jpa:
    open-in-view: false
server:
  port: 8081

cache:
  code:
    ttl: 30

mq:
  exchange: id-service.exchange
  privacy-policy-exchange: privacy-policy.exchange
  routing-key:
    service-registration: service.registered
    verification-code: code.generated