#file: noinspection undefined
spring:
  application:
    name: dev-id-service
  docker:
    compose:
      enabled: true
      file:
        - identity-service/docker-build/docker-compose.yml
  devtools:
    add-properties: true
  liquibase:
    change-log: db/changelog/db.changelog-master-dev.yml
  rabbitmq:
    password: developer
    username: developer
    virtual-host: /

logging:
  level:
    web: debug

policy:
  endpoints:
    file-path: ./identity-service/policy/endpoints.yml
