spring:
  application:
    name: identity-service
  profiles:
    active: dev
  jpa:
    open-in-view: false

server:
  port: 8081

cache:
  code:
    ttl: 30

mq:
  exchange: id-service
  routing-key:
    verification-code: code-generated