version: '2.38.1'

services:
  rabbit:
    container_name: rabbit
    image: re1kur/pra-rabbit:v1
    build:
      dockerfile: rabbitmq/Dockerfile
    env_file: rabbitmq/rabbitmq.env
    networks:
      - pra

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - file-service
      - identity-service
      - authz-service
      - parking-service
    ports:
      - "8080:80"
    networks:
      - pra

  #------------------------------------------------------------------------------------------

  authz-redis:
    container_name: authz-redis
    image: redis:8-alpine3.21
    networks:
      - pra

  authz-postgres:
    container_name: authz-postgres
    image: postgres:17-alpine
    env_file:
      - authz-service/docker-build/sql.env
    networks:
      - pra

  authz-service:
    container_name: authz
    image: re1kur/pra-authz:v1
    build:
      dockerfile: authz-service/docker-build/Dockerfile
      context: .
    env_file:
      - authz-service/docker-build/sql.env
      - authz-service/docker-build/redis.env
      - rabbitmq/rabbitmq.env
    hostname: authz-service
    depends_on:
      - rabbit
      - authz-postgres
      - authz-redis
    networks:
      - pra

  #------------------------------------------------------------------------------------------

  id-redis:
    container_name: id-redis
    image: redis:8-alpine3.21
    networks:
      - pra

  id-postgres:
    container_name: id-postgres
    image: postgres:17-alpine
    env_file:
      - identity-service/docker-build/sql.env
    networks:
      - pra

  identity-service:
    container_name: id
    image: re1kur/pra-id:v1
    volumes:
      - ./identity-service/policy/endpoints.yml:/policy/endpoints.yml
    build:
      dockerfile: identity-service/docker-build/Dockerfile
      context: .
    env_file:
      - identity-service/docker-build/sql.env
      - identity-service/docker-build/redis.env
      - rabbitmq/rabbitmq.env
    hostname: identity-service
    depends_on:
      - rabbit
      - id-postgres
      - id-redis
    networks:
      - pra

  #------------------------------------------------------------------------------------------

  fs-postgres:
    container_name: fs-postgres
    image: postgres:17-alpine
    env_file:
      - file-service/docker-build/sql.env
    networks:
      - pra
  fs-minio:
    container_name: fs-minio
    image: quay.io/minio/minio:latest
    env_file:
      - file-service/docker-build/minio.env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
    networks:
      - pra
  file-service:
    container_name: fs
    image: re1kur/pra-fs:v1
    volumes:
      - ./file-service/policy/endpoints.yml:/policy/endpoints.yml
    build:
      dockerfile: file-service/docker-build/Dockerfile
      context: .
    env_file:
      - file-service/docker-build/sql.env
      - file-service/docker-build/minio.env
      - rabbitmq/rabbitmq.env
    hostname: file-service
    depends_on:
      - rabbit
      - fs-postgres
      - fs-minio
    networks:
      - pra

  #------------------------------------------------------------------------------------------

  notification-service:
    container_name: ns
    image: re1kur/pra-ns:v1
    build:
      dockerfile: notification-service/docker-build/Dockerfile
      context: .
    env_file:
      - notification-service/docker-build/variables.env
      - rabbitmq/rabbitmq.env
    depends_on:
      - rabbit
    networks:
      - pra

  #------------------------------------------------------------------------------------------

  ps-postgres:
    container_name: ps-postgres
    image: postgres:17-alpine
    env_file:
      - parking-service/docker-build/sql.env
    networks:
      - pra

  parking-service:
    image: re1kur/pra-ps:v1
    container_name: ps
    volumes:
      - ./parking-service/policy/endpoints.yml:/policy/endpoints.yml
    build:
      dockerfile: parking-service/docker-build/Dockerfile
      context: .
    env_file:
      - parking-service/docker-build/sql.env
      - rabbitmq/rabbitmq.env
    depends_on:
      - rabbit
      - ps-postgres
    networks:
      - pra

#------------------------------------------------------------------------------------------

networks:
  pra:
    external: false
    driver: bridge
    name: pra-bridge