name: dev-pra
services:
  rabbit:
    env_file: rabbitmq/rabbitmq.env
    build: rabbitmq/.
    ports:
      - "5672:5672"
      - "15672:15672"
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"