spring:
  application:
    name: authz-service
  profiles:
    active: dev
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
server:
  port: 8082

jwt:
  claim-name:
    roles: scope
  ttl-hours: 12
  refresh-ttl-days: 7
  keySize: 2048
  privateKeyPath: /tmp/private.key
  publicKeyPath: /tmp/public.key
  kidPath: /tmp/kid.txt

mq:
  listen:
    service-registered-queue: service.registered.queue
