spring:
  application:
    name: authz-service
  profiles:
    active: dev
server:
  port: 8082

custom:
  jwt:
    ttl-hours: 12
    refresh-ttl-days: 7
    keySize: 2048
    privateKeyPath: /tmp/private.key
    publicKeyPath: /tmp/public.key
    kidPath: /tmp/kid.txt