#file: noinspection undefined
spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  devtools:
    add-properties: false
  docker:
    compose:
      enabled: false
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}


client:
  identity-service:
    login-endpoint: http://identity-service:8081/api/auth/login