#file: noinspection undefined
spring:
  docker:
    compose:
      enabled: true
      file: authz-service/docker-build/docker-compose.yml
  devtools:
    add-properties: true
  rabbitmq:
    password: developer
    username: developer
    virtual-host: /

client:
  identity-service:
    login-endpoint: http://localhost:8081/api/auth/login

logging:
  level:
    web: debug