name: dev-pra-id-service
services:
  postgres:
    image: postgres:17
    environment:
      - "POSTGRES_DB=develop"
      - "POSTGRES_PASSWORD=develop"
      - "POSTGRES_USER=develop"
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6380:6379"