#file: noinspection undefined
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  docker:
    compose:
      enabled: false

minio:
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  endpoint: ${MINIO_ENDPOINT}
  endpoint-override: ${MINIO_ENDPOINT_OVERRIDE}
  url:
    time-to-live: 7
  default-bucket: default-bucket