#file: noinspection undefined
spring:
  application:
    name: file-service
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  jpa:
    open-in-view: false
server:
  port: 8085

mq:
  privacy-policy-exchange: privacy-policy.exchange
  routing-key:
    service-registration: service.registered