#file: noinspection undefined
spring:
  application:
    name: parking-service
  jpa:
    open-in-view: false
  sql:
    init:
      mode: never
server:
  port: 8083

mq:
  privacy-policy-exchange: privacy-policy.exchange
  routing-key:
    service-registration: service.registered