#file: noinspection undefined
spring:
  docker:
    compose:
      enabled: true
      file: parking-service/docker-build/docker-compose.yml
  devtools:
    add-properties: true

  jpa:
    show-sql: true

client:
  identity-service:
    identify-endpoint: http://localhost:8081/api/users/identify