version: '2.38.1'

services:
  devpra-ps-psql:
    container_name: devpra-ps-psql
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_USER=developer
    ports:
      - '5431:5432'